### ISSUE TITLE
Quotes JSON naming convention

### ISSUE THREAD

**Issue by TheLearneer** [NITJSR-OSS/EverydayFun#22]
It is a good idea to follow **camelCase** for JSON objects. But the Quotes JSON file does it other way.

I planned to implement this as well in my PR, but then the open PR could not be merged. Also I wanted to know you thoughts on this before that.

**Comment by tachodril** [comment]
Thanks @TheLearneer  for pointing this out.
This is indeed a good idea.

**Comment by TheLearneer** [comment]
@tachodril You there, I need to talk to you about few things regarding the changes.
